#!/usr/bin/env sh

npm version patch -w api --no-git-tag-version
git add apps/services/api/package.json

npm version patch -w ems-web --no-git-tag-version
git add apps/web/package.json

git commit -m "chore: bump versions" --no-verify
