name: EMS CD - Deploy to AWS ECR

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  id-token: write # required for AWS OIDC authentication

env:
  BRANCH_NAME: ${{ github.ref_name }}
  COMMIT_SHA: ${{ github.sha }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::102536421230:role/GitHubActionsECRPush
          aws-region: us-east-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push Backend Docker image
        run: |
          docker build --target backend -t ems-backend:latest -t 102536421230.dkr.ecr.us-east-2.amazonaws.com/ems-backend:latest -t 102536421230.dkr.ecr.us-east-2.amazonaws.com/ems-backend:${BRANCH_NAME}-${COMMIT_SHA} .
          docker push 102536421230.dkr.ecr.us-east-2.amazonaws.com/ems-backend:latest
          docker push 102536421230.dkr.ecr.us-east-2.amazonaws.com/ems-backend:${BRANCH_NAME}-${COMMIT_SHA}

      - name: Build and push Web Docker image
        run: |
          docker build --target web -t ems-web:latest -t 102536421230.dkr.ecr.us-east-2.amazonaws.com/ems-web:latest -t 102536421230.dkr.ecr.us-east-2.amazonaws.com/ems-web:${BRANCH_NAME}-${COMMIT_SHA} .
          docker push 102536421230.dkr.ecr.us-east-2.amazonaws.com/ems-web:latest
          docker push 102536421230.dkr.ecr.us-east-2.amazonaws.com/ems-web:${BRANCH_NAME}-${COMMIT_SHA}
