name: EMS CI Build

on:
  push:
    branches:
      - "*"
  workflow_dispatch:

jobs:
  build:
    name: Build All
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Detect changes
        id: changed
        uses: tj-actions/changed-files@v34
        with:
          files: |
            apps/**
            libs/**

      - name: Use Node.js 20.x
        if: steps.changed.outputs.any_changed == 'true'
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: Install dependencies
        if: steps.changed.outputs.any_changed == 'true'
        run: |
          npm i

      - name: Build turborepo
        if: steps.changed.outputs.any_changed == 'true'
        run: |
          npm run build
